name: RDP HenCoders

on:
  workflow_dispatch:

jobs:
  setup_windows_rdp_runner:
    runs-on: windows-latest

    steps:
    - name: Setup Directory and Download Runner
      run: |
        mkdir C:\actions-runner
        cd C:\actions-runner
        Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-win-x64-2.321.0.zip -OutFile actions-runner.zip
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\actions-runner\actions-runner.zip", "C:\actions-runner")
        Write-Output "Runner downloaded and extracted."

    - name: Configure Runner with Automatic Input
      run: |
        cd C:\actions-runner
        $input = @"
Y
Y
"@
        $input | Out-File -FilePath input.txt -Encoding ASCII
        Start-Process -FilePath "cmd.exe" -ArgumentList "/c config.cmd --url https://github.com/HenDeveloper/HenRdp --token ${{ secrets.TOKEN }} < input.txt" -Wait
        Write-Output "Runner configured successfully."

    - name: Install and Start Runner Service
      run: |
        cd C:\actions-runner
        echo "Y" | .\svc.cmd install
        echo "Y" | .\svc.cmd start
        Write-Output "Runner service installed and started."

    - name: Setup Tailscale
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup-latest.exe
        Start-Process .\tailscale-setup-latest.exe -ArgumentList "/quiet" -Wait
        tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
        Write-Output "Tailscale setup complete."

    - name: Enable Remote Desktop (RDP)
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Output "RDP enabled."
