name: RDP HenCoders

on:
  workflow_dispatch:

jobs:
  setup_windows_rdp_runner:
    runs-on: windows-latest

    steps:
    - name: Download and Extract Self-Hosted Runner
      run: |
        mkdir C:\actions-runner
        cd C:\actions-runner
        
        # Download runner
        Write-Output "Downloading self-hosted runner..."
        Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-win-x64-2.321.0.zip -OutFile actions-runner.zip
        
        # Verify the download
        if (-not (Test-Path "C:\actions-runner\actions-runner.zip")) {
          throw "Runner ZIP file not found. Download failed."
        }
        Write-Output "Runner ZIP file downloaded successfully."
        
        # Extract runner
        Write-Output "Extracting self-hosted runner..."
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\actions-runner\actions-runner.zip", "C:\actions-runner")
        
        # Verify extraction
        if (-not (Test-Path "C:\actions-runner\svc.cmd")) {
          throw "svc.cmd not found. Extraction failed."
        }
        Write-Output "Self-hosted runner extracted successfully."

    - name: Configure Self-Hosted Runner
      run: |
        cd C:\actions-runner
        .\config.cmd --url https://github.com/HenDeveloper/HenRdp --token ${{ secrets.TOKEN }}
        Write-Output "Self-hosted runner configured successfully."

    - name: Install and Start Self-Hosted Runner Service
      run: |
        cd C:\actions-runner
        .\svc.cmd install
        .\svc.cmd start
        Write-Output "Self-hosted runner service installed and started successfully."

    - name: Setup Tailscale
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-ipn-setup.exe -OutFile tailscale-ipn-setup.exe
        Start-Process .\tailscale-ipn-setup.exe -ArgumentList "/quiet" -Wait
        tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}
        Write-Output "Tailscale setup complete."

    - name: Enable Remote Desktop (RDP)
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Output "Remote Desktop enabled successfully."

    - name: Set Wallpaper
      run: |
        $wallpaperUrl = "https://s13.gifyu.com/images/SJ7tu.jpg"
        $wallpaperPath = "$env:USERPROFILE\Desktop\HenCodersWallpaper.jpg"
        Invoke-WebRequest -Uri $wallpaperUrl -OutFile $wallpaperPath
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d $wallpaperPath /f
        reg add "HKCU\Control Panel\Desktop" /v WallpaperStyle /t REG_SZ /d 10 /f
        RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters
        Write-Output "Wallpaper applied successfully."

    - name: Add Branding to Desktop
      run: |
        $brandingText = "Copyright © HenCoders 2024\nAll rights reserved."
        $desktopPath = "$env:USERPROFILE\Desktop"
        Set-Content -Path "$desktopPath\HenCoders_Info.txt" -Value $brandingText
        Write-Output "Branding added to desktop."

    - name: Display RDP Login Details
      run: |
        $tailscaleIp = (tailscale ip -4).Trim()
        Write-Output "================================"
        Write-Output "RDP Login Details:"
        Write-Output "IP RDP: $tailscaleIp"
        Write-Output "Username: administrator"
        Write-Output "Password: HenCoders2024"
        Write-Output "================================"
